### ISSUE TITLE
Make Code of Conduct mandatory for conferences by 2021 ✔️

### ISSUE THREAD

**Issue by coderbyheart** [softwarecrafters/website#130]
Hei :wave: friends,

I have taken on the task of merging #72. As a community we are already close to be able to implement this because right now the majority of conferences already provide a link to a code of conduct:

| Conference | Code of Conduct | Contact |
|-------|-------|------|
| AgileCrete | - | @gsaslis |
| Codefreeze | <https://codefreeze.fi/#code-of-conduct> | |
| DevTernity | <https://devternity.com/code_of_conduct.html> | |
| #humansconf | <https://www.humansconf.org/code-of-conduct> | |
| I T.A.K.E. Unconference | <https://itakeunconf.com/code-of-conduct/> | |
| JSCraftcamp | http://jscraftcamp.org/values | |
| Mob Programming Conference | <https://mobprogrammingnewengland.com/code-of-conduct> | |
| Software Crafters Unconference | https://scunconf.com/#coc | |
| SoCraTes Austria 2019 | <http://socrates-conference.at/en/code-of-conduct/> | |
| SoCraTes Belgium | <http://socratesbe.org/#coc> | |
| SoCraTes Canada | <https://socrates-ca.github.io/#portfolioModal2> | |
| ~~SoCraTes Canaries~~ | ~~<http://socracan.com/#coc>~~ (404) | |
| SoCraTes Switzerland | <https://www.socrates-ch.org/#code-of-conduct> | |
| SoCraTes Day Berlin | <https://www.socratesday.berlin> | |
| SoCraTes Day Switzerland | - | @ollin |
| ~~SoCraTes Day Franconia~~ | ~~<http://socrates-day-franken.de/>~~ (404) | |
| SoCraTes Germany | <https://www.socrates-conference.de/values> | |
| SoCraTes Rennes | <https://socrates-rennes.github.io/#a-propos> | |
| SoCraTes France | <https://socrates-fr.github.io/#portfolioModal2> | |
| SoCraTes Italy | <http://www.socrates-conference.it/> | |
| SoCraTes UK | <https://socratesuk.org/code_of_conduct.html> | |
| Software Crafters Barcelona | <https://scbcn.github.io/coc.html> | |
| Software Engineering Camp | - | @poschi3 |

## Rationale

The Software Crafters community believes in inclusivity. Only through providing a safe and welcoming environment to everyone who wants to engage in events promoted by us will we grow personally and as an industry in a meaningful and responsible way. While there exists not *one* code of conduct that can apply to all types of events, we recognize however [the Code of Conduct of the SoCraTes conference in Germany](https://www.socrates-conference.de/values) as a great example. It has been served other events as a good example and we encourage conference organizers to adapt, but **not copy verbatim**, its contents to suit their event and team.

## Proposed actions

In order to resolve this issue I propose these actions:

- **Existing conferences:** I would kindly ask the remaining conference organizers (mentioned above) to adopt a Code of Conduct by the end of 2020. A good example for a Code of Conduct is <https://socrates-conference.de/values>.
- As soon as all existing conferences have provided a Code of Contact link, merge #72 so that it is enforced immediately for new entries.
- **New conferences:** All new entries for conferences **must** provide a link to a Code of Conduct as of today.
- Conference entries without a valid Code of Conduct will be removed in January 2021.

**Comment by gsaslis** [comment]
@coderbyheart thank you so much for taking this on! 

For AgileCrete this was on our to-fix list for 2020 already, but then... 2020 happened, so we never got round to finalising / publishing it. I've contacted the rest of the org team and I expect we'll have it sorted by the end of the month. 

By the way: if you want to enforce this straight away, it is absolutely fine if AgileCrete is removed from the list (temporarily, while we get that fixed). I wouldn't want to keep the rest of you waiting and risk other conferences making it onto the list without a CoC in the meantime.

**Comment by coderbyheart** [comment]
Great, as I mentioned there is time until end of 2020, so I am fine with waiting a little bit longer. Great to hear that you are on it, and hopefully can put it to good use in a physical event soon!

**Comment by coderbyheart** [comment]
The PR making this mandatory is ready: https://github.com/softwarecrafters/website/pull/72
