### ISSUE TITLE
Software Crafters Rhein Main is on the wrong continent 

### ISSUE THREAD

**Issue by franziskas** [softwarecrafters/website#31]
![screenshot_20170915-095627](https://user-images.githubusercontent.com/5154737/30472352-3bf0a978-99fc-11e7-960d-c4a3a0333277.png)

This was added by @svenlange in https://github.com/softwarecrafters/website/pull/27

Maybe you can fix it as well? :)

**Comment by rradczewski** [comment]
Fixed in a816d38

**Comment by svenlange** [comment]
Thx
